In [1]:
import numpy as np

In [19]:
skalar = np.array(5)

In [20]:
skalar

array(5)

In [9]:
vector = np.array([3,2,4])

In [10]:
vector

array([3, 2, 4])

In [12]:
matrix = np.array([[3,-9,2],[1,7,4]])

In [13]:
matrix

array([[ 3, -9,  2],
       [ 1,  7,  4]])

In [15]:
type(skalar)

int

In [16]:
type(vector)

numpy.ndarray

In [17]:
type(matrix)

numpy.ndarray

In [21]:
skalar.shape

()

In [22]:
vector.shape

(3,)

In [23]:
vector.reshape(1,3)

array([[3, 2, 4]])

In [24]:
vector.reshape(3,1)

array([[3],
       [2],
       [4]])

In [25]:
matrix.shape

(2, 3)